CREATE PROCEDURE [DBO].[SP_AUDITPROCEDURECARTEIRACONTENT] AS 

BEGIN 

	SET NOCOUNT ON; 

	SELECT

		  CED.ID_CEDENTE 
		, CED.NM_CEDENTE 
		, CONT_DT_CAD = MAX(CONT.DT_CADASTRO)

	INTO #MAIN_CONTRATOS 
	FROM TB_CLIENTE		CLI		WITH(NOLOCK)
	JOIN TB_CONTRATO	CONT	WITH(NOLOCK) ON CLI.ID_CLIENTE = CONT.ID_CLIENTE 
	JOIN TB_DIVIDA		DIV		WITH(NOLOCK) ON CONT.ID_CONTRATO = DIV.ID_CONTRATO 
	JOIN TB_CEDENTE		CED		WITH(NOLOCK) ON CLI.ID_CEDENTE = CED.ID_CEDENTE 
	WHERE
		  CAST(CONT.DT_CADASTRO AS DATE) = CAST(GETDATE() AS DATE) 
	GROUP BY
		  CED.ID_CEDENTE
		, CED.NM_CEDENTE


	SELECT

		  CED.ID_CEDENTE 
		, CED.NM_CEDENTE 
		, CONT_DT_CAD = MAX(CLI.DT_CADASTRO)
	
	INTO #MAIN_CLIENTES 
	FROM TB_CLIENTE CLI WITH(NOLOCK) 
	JOIN TB_CEDENTE CED WITH(NOLOCK) ON CLI.ID_CEDENTE = CED.ID_CEDENTE 
	WHERE
		  CAST(CLI.DT_CADASTRO AS DATE) = CAST(GETDATE() AS DATE) 
	AND
		  CLI.ID_CEDENTE NOT IN (SELECT ID_CEDENTE FROM #MAIN_CONTRATOS)
	GROUP BY
		  CED.ID_CEDENTE
		, CED.NM_CEDENTE


	SELECT * INTO #MAIN FROM #MAIN_CONTRATOS 
	UNION ALL 
	SELECT * FROM #MAIN_CLIENTES


	DECLARE @ID_CEDENTE INT;
	SELECT	@ID_CEDENTE = ID_CEDENTE FROM #MAIN 

	DECLARE @ID_CURSOR INT; 
	DECLARE @CEDENTE_CURSOR VARCHAR(100);
	DECLARE @DT_CAD_CURSOR DATETIME;

	DECLARE CURSOR_A CURSOR FOR 
	SELECT
	ID_CEDENTE , NM_CEDENTE, CONT_DT_CAD
	FROM #MAIN; 

	OPEN CURSOR_A;

	FETCH NEXT FROM CURSOR_A INTO @ID_CURSOR, @CEDENTE_CURSOR,@DT_CAD_CURSOR;
	WHILE @@FETCH_STATUS = 0 
	BEGIN 
		  IF NOT EXISTS (SELECT ID_CEDENTE FROM TB_MIS_LOG_CARGA WHERE ID_CEDENTE = @ID_CURSOR) BEGIN 
				INSERT INTO TB_MIS_LOG_CARGA VALUES (@ID_CURSOR,@CEDENTE_CURSOR, @DT_CAD_CURSOR,1,0,NULL);
				DECLARE @PRC AS VARCHAR(100); 
				SELECT  @PRC = NM_PRC_TABELA FROM TB_TABELA_VISAO_CARTEIRA WHERE ID_CEDENTE = @ID_CURSOR;
				EXEC @PRC;
		  END;
		  IF EXISTS (SELECT ID_CEDENTE FROM TB_MIS_LOG_CARGA WHERE ID_CEDENTE = @ID_CURSOR AND CONT_DT_CAD <> @DT_CAD_CURSOR ) BEGIN 
				UPDATE TB_MIS_LOG_CARGA SET CONT_DT_CAD = @DT_CAD_CURSOR, FLAG_UPDATE = 1 WHERE ID_CEDENTE = @ID_CURSOR;
		  END;
	FETCH NEXT FROM CURSOR_A INTO @ID_CURSOR, @CEDENTE_CURSOR,@DT_CAD_CURSOR;
	END;
	CLOSE CURSOR_A;
	DEALLOCATE CURSOR_A;

	COMMIT;

	DROP TABLE #MAIN; 
	DROP TABLE #MAIN_CLIENTES; 
	DROP TABLE #MAIN_CONTRATOS;

END;
